---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-domain-tld-cert
  namespace: mailserver
spec:
  commonName: mail01.domain.tld
  secretName: mail-domain-tld-cert
  dnsNames:
    - mail01.domain.tld
    - mail02.domain.tld
    - mail03.domain.tld
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
