kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mailserver
  name: postfix
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - secrets
  resourceNames:
    - postfix
  verbs:
    - get
